import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '../styles/reset.css';
import Header from '@/components/Header';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pl'>
      <body className={montserrat.variable}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
